dist: bionic
language: generic

before_install:
  - |
      echo "Checking if a CI run is needed post commit: ${TRAVIS_COMMIT_RANGE}"
      if ! git diff --name-only ${TRAVIS_COMMIT_RANGE} | grep -qvE '(\.png$)|(\.pdf$)|(\.html$)|^(LICENSE)'
      then
        echo "Only doc files were updated, not running the CI."
        exit
      fi
  - sudo add-apt-repository --yes ppa:js-reynaud/kicad-5.1
  - sudo apt update -y
  - sudo apt install --no-install-recommends -y kicad kicad-symbols kicad-templates kicad-footprints inkscape

script:
  - cd scripts && /pcb2svg.sh && cd ..

